In [3]:
import math
num = 25
result = math.sqrt(num)
print(result)

5.0


In [5]:
from math import sqrt
num = 1000
result = sqrt(num)
print(result)

31.622776601683793


In [6]:
from math import *
num = 25
square_root = sqrt(num)
circumference = 2 * pi
print(f"Square root of {num} is {square_root}.")
print(f"Circumference of a Circle with radius 1 is {circumference}.")

Square root of 25 is 5.0.
Circumference of a Circle with radius 1 is 6.283185307179586.


In [8]:
import numpy as np
num_list = [1, 2, 3, 4, 5]
arr_1D = np.array(num_list)
print(arr_1D)

[1 2 3 4 5]


In [9]:
import numpy as np
arr_1D = np.array([1, 2, 3, 4, 5])
print(arr_1D)

[1 2 3 4 5]


In [11]:
import numpy as np
arr_2D = np.array([[1, 2, 3], [4, 5, 6]])
print(arr_2D)

[[1 2 3]
 [4 5 6]]


In [12]:
import numpy as np
arr_3D = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(arr_3D)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [14]:
import numpy as np
zeros_arr_2D = np.zeros((4, 4))
print(zeros_arr_2D)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [15]:
import numpy as np
ones_arr_1D = np.ones(4)
print(ones_arr_1D)

[1. 1. 1. 1.]


In [19]:
import numpy as np
arr_1D = np.array([1, 2, 3, 4])
result1 = arr_1D + 10
print(result1)
result2 = arr_1D - 4
print(result2)
result3 = arr_1D * 2
print(result3)
result4  = arr_1D / 2
print(result4)

[11 12 13 14]
[-3 -2 -1  0]
[2 4 6 8]
[0.5 1.  1.5 2. ]
